name: Build Binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Build Linux binary
        run: bun run compile:linux
      - name: Build Windows binary
        run: bun run compile:windows
      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: nzch-linux
          path: nzch
      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: nzch-windows
          path: nzch.exe
